// nihongo-quest data — extracted from github.com/alen60335/nihongo (nihongo.html)
// HIRA/KATA: 50-sound kana; VDB: 4wk x 7day x 15 words; GDB: 12 grammar points w/ quizzes; REF: cheat sheets
var HIRA=[['あ','a'],['い','i'],['う','u'],['え','e'],['お','o'],['か','ka'],['き','ki'],['く','ku'],['け','ke'],['こ','ko'],['さ','sa'],['し','shi'],['す','su'],['せ','se'],['そ','so'],['た','ta'],['ち','chi'],['つ','tsu'],['て','te'],['と','to'],['な','na'],['に','ni'],['ぬ','nu'],['ね','ne'],['の','no'],['は','ha'],['ひ','hi'],['ふ','fu'],['へ','he'],['ほ','ho'],['ま','ma'],['み','mi'],['む','mu'],['め','me'],['も','mo'],['や','ya'],['',''],['ゆ','yu'],['',''],['よ','yo'],['ら','ra'],['り','ri'],['る','ru'],['れ','re'],['ろ','ro'],['わ','wa'],['',''],['',''],['',''],['を','wo'],['ん','n'],['',''],['',''],['',''],['','']];
var KATA=[['ア','a'],['イ','i'],['ウ','u'],['エ','e'],['オ','o'],['カ','ka'],['キ','ki'],['ク','ku'],['ケ','ke'],['コ','ko'],['サ','sa'],['シ','shi'],['ス','su'],['セ','se'],['ソ','so'],['タ','ta'],['チ','chi'],['ツ','tsu'],['テ','te'],['ト','to'],['ナ','na'],['ニ','ni'],['ヌ','nu'],['ネ','ne'],['ノ','no'],['ハ','ha'],['ヒ','hi'],['フ','fu'],['ヘ','he'],['ホ','ho'],['マ','ma'],['ミ','mi'],['ム','mu'],['メ','me'],['モ','mo'],['ヤ','ya'],['',''],['ユ','yu'],['',''],['ヨ','yo'],['ラ','ra'],['リ','ri'],['ル','ru'],['レ','re'],['ロ','ro'],['ワ','wa'],['',''],['',''],['',''],['ヲ','wo'],['ン','n'],['',''],['',''],['',''],['','']];
var VDB=[
  {week:1,day:1,theme:'打招呼',words:[{jp:'おはよう',rd:'ohayou',zh:'早安（輕鬆）'},{jp:'おはようございます',rd:'ohayou gozaimasu',zh:'早安（正式）'},{jp:'こんにちは',rd:'konnichiwa',zh:'你好／午安'},{jp:'こんばんは',rd:'konbanwa',zh:'晚安（問候）'},{jp:'おやすみなさい',rd:'oyasumi nasai',zh:'晚安（睡前）'},{jp:'さようなら',rd:'sayounara',zh:'再見'},{jp:'またね',rd:'matane',zh:'拜拜'},{jp:'はじめまして',rd:'hajimemashite',zh:'初次見面'},{jp:'よろしく',rd:'yoroshiku',zh:'請多指教（輕鬆）'},{jp:'よろしくおねがいします',rd:'yoroshiku onegaishimasu',zh:'請多指教（正式）'},{jp:'おげんきですか',rd:'ogenki desu ka',zh:'你好嗎？'},{jp:'げんきです',rd:'genki desu',zh:'我很好'},{jp:'ありがとう',rd:'arigatou',zh:'謝謝（輕鬆）'},{jp:'ありがとうございます',rd:'arigatou gozaimasu',zh:'謝謝（正式）'},{jp:'どういたしまして',rd:'dou itashimashite',zh:'不客氣'}]},
  {week:1,day:2,theme:'基本應答',words:[{jp:'はい',rd:'hai',zh:'是'},{jp:'いいえ',rd:'iie',zh:'不是'},{jp:'そうです',rd:'sou desu',zh:'對、是的'},{jp:'ちがいます',rd:'chigaimasu',zh:'不對'},{jp:'わかりました',rd:'wakarimashita',zh:'我明白了'},{jp:'わかりません',rd:'wakarimasen',zh:'我不懂'},{jp:'しりません',rd:'shirimasen',zh:'我不知道'},{jp:'すみません',rd:'sumimasen',zh:'不好意思'},{jp:'ごめんなさい',rd:'gomen nasai',zh:'對不起'},{jp:'だいじょうぶ',rd:'daijoubu',zh:'沒關係'},{jp:'もういちど',rd:'mou ichido',zh:'再說一次'},{jp:'ゆっくり',rd:'yukkuri',zh:'慢慢地'},{jp:'にほんご',rd:'nihongo',zh:'日文'},{jp:'えいご',rd:'eigo',zh:'英文'},{jp:'ちゅうごくご',rd:'chuugokugo',zh:'中文'}]},
  {week:1,day:3,theme:'數字1-15',words:[{jp:'いち',rd:'ichi',zh:'1'},{jp:'に',rd:'ni',zh:'2'},{jp:'さん',rd:'san',zh:'3'},{jp:'し／よん',rd:'shi/yon',zh:'4'},{jp:'ご',rd:'go',zh:'5'},{jp:'ろく',rd:'roku',zh:'6'},{jp:'しち／なな',rd:'shichi/nana',zh:'7'},{jp:'はち',rd:'hachi',zh:'8'},{jp:'く／きゅう',rd:'ku/kyuu',zh:'9'},{jp:'じゅう',rd:'juu',zh:'10'},{jp:'じゅういち',rd:'juuichi',zh:'11'},{jp:'じゅうに',rd:'juuni',zh:'12'},{jp:'じゅうさん',rd:'juusan',zh:'13'},{jp:'じゅうし',rd:'juushi',zh:'14'},{jp:'じゅうご',rd:'juugo',zh:'15'}]},
  {week:1,day:4,theme:'數字16-大數',words:[{jp:'じゅうろく',rd:'juuroku',zh:'16'},{jp:'じゅうなな',rd:'juunana',zh:'17'},{jp:'じゅうはち',rd:'juuhachi',zh:'18'},{jp:'じゅうく',rd:'juuku',zh:'19'},{jp:'にじゅう',rd:'nijuu',zh:'20'},{jp:'さんじゅう',rd:'sanjuu',zh:'30'},{jp:'よんじゅう',rd:'yonjuu',zh:'40'},{jp:'ごじゅう',rd:'gojuu',zh:'50'},{jp:'ひゃく',rd:'hyaku',zh:'100'},{jp:'にひゃく',rd:'nihyaku',zh:'200'},{jp:'ごひゃく',rd:'gohyaku',zh:'500'},{jp:'せん',rd:'sen',zh:'1000'},{jp:'にせん',rd:'nisen',zh:'2000'},{jp:'ごせん',rd:'gosen',zh:'5000'},{jp:'いちまん',rd:'ichiman',zh:'10000'}]},
  {week:1,day:5,theme:'時間日期',words:[{jp:'いまなんじですか',rd:'ima nanji desu ka',zh:'現在幾點？'},{jp:'ごぜん',rd:'gozen',zh:'上午'},{jp:'ごご',rd:'gogo',zh:'下午'},{jp:'じ',rd:'ji',zh:'點（時刻）'},{jp:'ふん／ぷん',rd:'fun/pun',zh:'分鐘'},{jp:'きょう',rd:'kyou',zh:'今天'},{jp:'あした',rd:'ashita',zh:'明天'},{jp:'きのう',rd:'kinou',zh:'昨天'},{jp:'なんようび',rd:'nan youbi',zh:'星期幾？'},{jp:'げつようび',rd:'getsuyoubi',zh:'星期一'},{jp:'かようび',rd:'kayoubi',zh:'星期二'},{jp:'すいようび',rd:'suiyoubi',zh:'星期三'},{jp:'もくようび',rd:'mokuyoubi',zh:'星期四'},{jp:'きんようび',rd:'kinyoubi',zh:'星期五'},{jp:'どようび',rd:'doyoubi',zh:'星期六'}]},
  {week:1,day:6,theme:'地點方向',words:[{jp:'どこ',rd:'doko',zh:'哪裡'},{jp:'ここ',rd:'koko',zh:'這裡'},{jp:'そこ',rd:'soko',zh:'那裡'},{jp:'あそこ',rd:'asoko',zh:'那邊'},{jp:'みぎ',rd:'migi',zh:'右邊'},{jp:'ひだり',rd:'hidari',zh:'左邊'},{jp:'まっすぐ',rd:'massugu',zh:'直走'},{jp:'まえ',rd:'mae',zh:'前面'},{jp:'うしろ',rd:'ushiro',zh:'後面'},{jp:'となり',rd:'tonari',zh:'旁邊'},{jp:'ちかく',rd:'chikaku',zh:'附近'},{jp:'とおい',rd:'tooi',zh:'遠的'},{jp:'ちかい',rd:'chikai',zh:'近的'},{jp:'きた',rd:'kita',zh:'北'},{jp:'みなみ',rd:'minami',zh:'南'}]},
  {week:1,day:7,theme:'疑問詞',words:[{jp:'なに／なん',rd:'nani/nan',zh:'什麼'},{jp:'だれ',rd:'dare',zh:'誰'},{jp:'いつ',rd:'itsu',zh:'什麼時候'},{jp:'どこ',rd:'doko',zh:'哪裡'},{jp:'どれ',rd:'dore',zh:'哪一個'},{jp:'どう',rd:'dou',zh:'怎樣'},{jp:'なぜ',rd:'naze',zh:'為什麼'},{jp:'いくら',rd:'ikura',zh:'多少錢'},{jp:'いくつ',rd:'ikutsu',zh:'幾個'},{jp:'なんにん',rd:'nannin',zh:'幾個人'},{jp:'なんじ',rd:'nanji',zh:'幾點'},{jp:'なんにち',rd:'nannichi',zh:'幾號'},{jp:'どんな',rd:'donna',zh:'什麼樣的'},{jp:'どのくらい',rd:'dono kurai',zh:'多久'},{jp:'なんで',rd:'nande',zh:'為什麼（口語）'}]},
  {week:2,day:1,theme:'食物',words:[{jp:'ごはん',rd:'gohan',zh:'米飯'},{jp:'すし',rd:'sushi',zh:'壽司'},{jp:'ラーメン',rd:'raamen',zh:'拉麵'},{jp:'てんぷら',rd:'tenpura',zh:'天婦羅'},{jp:'そば',rd:'soba',zh:'蕎麥麵'},{jp:'うどん',rd:'udon',zh:'烏龍麵'},{jp:'やきとり',rd:'yakitori',zh:'烤雞串'},{jp:'たこやき',rd:'takoyaki',zh:'章魚燒'},{jp:'おにぎり',rd:'onigiri',zh:'飯糰'},{jp:'べんとう',rd:'bentou',zh:'便當'},{jp:'みそしる',rd:'misoshiru',zh:'味噌湯'},{jp:'さしみ',rd:'sashimi',zh:'生魚片'},{jp:'とんかつ',rd:'tonkatsu',zh:'豬排'},{jp:'カレー',rd:'karee',zh:'咖哩'},{jp:'アイスクリーム',rd:'aisu kuriimu',zh:'冰淇淋'}]},
  {week:2,day:2,theme:'飲料',words:[{jp:'みず',rd:'mizu',zh:'水'},{jp:'おちゃ',rd:'ocha',zh:'茶'},{jp:'こうちゃ',rd:'koucha',zh:'紅茶'},{jp:'コーヒー',rd:'koohii',zh:'咖啡'},{jp:'ジュース',rd:'juusu',zh:'果汁'},{jp:'ビール',rd:'biiru',zh:'啤酒'},{jp:'さけ',rd:'sake',zh:'日本酒'},{jp:'コーラ',rd:'koora',zh:'可樂'},{jp:'ミルク',rd:'miruku',zh:'牛奶'},{jp:'ぬるい',rd:'nurui',zh:'溫的'},{jp:'つめたい',rd:'tsumetai',zh:'冷的'},{jp:'あつい',rd:'atsui',zh:'熱的'},{jp:'あまい',rd:'amai',zh:'甜的'},{jp:'からい',rd:'karai',zh:'辣的'},{jp:'しおからい',rd:'shiokarai',zh:'鹹的'}]},
  {week:2,day:3,theme:'餐廳點餐',words:[{jp:'メニュー',rd:'menyuu',zh:'菜單'},{jp:'ちゅうもん',rd:'chuumon',zh:'點餐'},{jp:'おすすめ',rd:'osusume',zh:'推薦'},{jp:'これ',rd:'kore',zh:'這個'},{jp:'ひとつ',rd:'hitotsu',zh:'一個'},{jp:'ふたつ',rd:'futatsu',zh:'兩個'},{jp:'みっつ',rd:'mittsu',zh:'三個'},{jp:'ください',rd:'kudasai',zh:'請給我'},{jp:'おなじもの',rd:'onaji mono',zh:'一樣的'},{jp:'セット',rd:'setto',zh:'套餐'},{jp:'おいしい',rd:'oishii',zh:'好吃'},{jp:'まずい',rd:'mazui',zh:'難吃'},{jp:'アレルギー',rd:'arerugii',zh:'過敏'},{jp:'ベジタリアン',rd:'bejitarian',zh:'素食者'},{jp:'もってきてください',rd:'motte kite kudasai',zh:'請拿過來'}]},
  {week:2,day:4,theme:'結帳付款',words:[{jp:'おかいけい',rd:'okaikei',zh:'買單'},{jp:'レシート',rd:'reshiito',zh:'收據'},{jp:'クレジットカード',rd:'kurejitto kaado',zh:'信用卡'},{jp:'げんきん',rd:'genkin',zh:'現金'},{jp:'おつり',rd:'otsuri',zh:'找零'},{jp:'わりかん',rd:'warikan',zh:'AA制'},{jp:'ねだん',rd:'nedan',zh:'價格'},{jp:'たかい',rd:'takai',zh:'貴的'},{jp:'やすい',rd:'yasui',zh:'便宜的'},{jp:'むりょう',rd:'muryou',zh:'免費'},{jp:'わりびき',rd:'waribiki',zh:'折扣'},{jp:'ポイント',rd:'pointo',zh:'點數'},{jp:'ぜいきん',rd:'zeikin',zh:'稅金'},{jp:'サービスりょう',rd:'saabisu ryou',zh:'服務費'},{jp:'ふくろ',rd:'fukuro',zh:'袋子'}]},
  {week:2,day:5,theme:'便利商店',words:[{jp:'コンビニ',rd:'konbini',zh:'便利商店'},{jp:'スーパー',rd:'suupaa',zh:'超市'},{jp:'ドラッグストア',rd:'doraggu sutoa',zh:'藥妝店'},{jp:'レジ',rd:'reji',zh:'收銀台'},{jp:'あたためますか',rd:'atatamemasu ka',zh:'需要加熱嗎？'},{jp:'はし',rd:'hashi',zh:'筷子'},{jp:'スプーン',rd:'supuun',zh:'湯匙'},{jp:'フォーク',rd:'fooku',zh:'叉子'},{jp:'しょうひきげん',rd:'shouhikigen',zh:'賞味期限'},{jp:'ぎゅうにゅう',rd:'gyuunyuu',zh:'牛奶'},{jp:'たまご',rd:'tamago',zh:'雞蛋'},{jp:'パン',rd:'pan',zh:'麵包'},{jp:'おにぎり',rd:'onigiri',zh:'飯糰'},{jp:'べんとう',rd:'bentou',zh:'便當'},{jp:'ジュース',rd:'juusu',zh:'果汁'}]},
  {week:2,day:6,theme:'購物',words:[{jp:'みせ',rd:'mise',zh:'店'},{jp:'まけてください',rd:'makete kudasai',zh:'算便宜一點'},{jp:'もうすこしやすく',rd:'mou sukoshi yasuku',zh:'再便宜一點'},{jp:'これはいくらですか',rd:'kore wa ikura desu ka',zh:'這個多少錢？'},{jp:'たくさんかいます',rd:'takusan kaimasu',zh:'我要買很多'},{jp:'まとめて',rd:'matomete',zh:'一起算'},{jp:'いろ',rd:'iro',zh:'顏色'},{jp:'サイズ',rd:'saizu',zh:'尺寸'},{jp:'ためしてみていいですか',rd:'tameshite mite ii desu ka',zh:'可以試試嗎？'},{jp:'にもつ',rd:'nimotsu',zh:'行李'},{jp:'おみやげ',rd:'omiyage',zh:'伴手禮'},{jp:'ふくろはいりますか',rd:'fukuro irimasu ka',zh:'需要袋子嗎？'},{jp:'カードでいいですか',rd:'kaado de ii desu ka',zh:'可以刷卡嗎？'},{jp:'レシートください',rd:'reshiito kudasai',zh:'請給收據'},{jp:'まとめていくらですか',rd:'matomete ikura desu ka',zh:'一共多少錢？'}]},
  {week:2,day:7,theme:'藥局健康',words:[{jp:'くすり',rd:'kusuri',zh:'藥'},{jp:'やっきょく',rd:'yakkyoku',zh:'藥局'},{jp:'いたい',rd:'itai',zh:'痛'},{jp:'あたまがいたい',rd:'atama ga itai',zh:'頭痛'},{jp:'おなかがいたい',rd:'onaka ga itai',zh:'肚子痛'},{jp:'はながでる',rd:'hana ga deru',zh:'流鼻水'},{jp:'せき',rd:'seki',zh:'咳嗽'},{jp:'ねつ',rd:'netsu',zh:'發燒'},{jp:'かぜ',rd:'kaze',zh:'感冒'},{jp:'アレルギー',rd:'arerugii',zh:'過敏'},{jp:'ばんそうこう',rd:'bansoukou',zh:'OK繃'},{jp:'げり',rd:'geri',zh:'拉肚子'},{jp:'はきけ',rd:'hakike',zh:'想吐'},{jp:'いしゃ',rd:'isha',zh:'醫生'},{jp:'びょういん',rd:'byouin',zh:'醫院'}]},
  {week:3,day:1,theme:'交通工具',words:[{jp:'でんしゃ',rd:'densha',zh:'電車'},{jp:'ちかてつ',rd:'chikatetsu',zh:'地鐵'},{jp:'バス',rd:'basu',zh:'公車'},{jp:'タクシー',rd:'takushii',zh:'計程車'},{jp:'しんかんせん',rd:'shinkansen',zh:'新幹線'},{jp:'ひこうき',rd:'hikouki',zh:'飛機'},{jp:'じてんしゃ',rd:'jitensha',zh:'腳踏車'},{jp:'のる',rd:'noru',zh:'搭乘'},{jp:'おりる',rd:'oriru',zh:'下車'},{jp:'のりかえ',rd:'norikae',zh:'換乘'},{jp:'ていりゅうじょ',rd:'teiryuujo',zh:'公車站'},{jp:'タクシーのりば',rd:'takushii noriba',zh:'計程車站'},{jp:'くうこう',rd:'kuukou',zh:'機場'},{jp:'あるく',rd:'aruku',zh:'走路'},{jp:'バスてい',rd:'basu tei',zh:'巴士站牌'}]},
  {week:3,day:2,theme:'車站電車',words:[{jp:'えき',rd:'eki',zh:'車站'},{jp:'かいさつ',rd:'kaisatsu',zh:'剪票口'},{jp:'ホーム',rd:'hoomu',zh:'月台'},{jp:'でぐち',rd:'deguchi',zh:'出口'},{jp:'いりぐち',rd:'iriguchi',zh:'入口'},{jp:'きっぷ',rd:'kippu',zh:'票'},{jp:'じどうけんばいき',rd:'jidou kenbaiki',zh:'自動售票機'},{jp:'Suica',rd:'suika',zh:'西瓜卡'},{jp:'ちゃーじ',rd:'chaaji',zh:'儲值'},{jp:'なんばんせん',rd:'nanban sen',zh:'幾號線？'},{jp:'つぎのでんしゃ',rd:'tsugi no densha',zh:'下一班電車'},{jp:'おくれ',rd:'okure',zh:'誤點'},{jp:'しゅうでん',rd:'shuuden',zh:'末班電車'},{jp:'じこくひょう',rd:'jikokuhyou',zh:'時刻表'},{jp:'のりこし',rd:'norikoshi',zh:'坐過站'}]},
  {week:3,day:3,theme:'問路',words:[{jp:'〜はどこですか',rd:'~wa doko desu ka',zh:'〜在哪裡？'},{jp:'まっすぐ',rd:'massugu',zh:'直走'},{jp:'みぎにまがる',rd:'migi ni magaru',zh:'右轉'},{jp:'ひだりにまがる',rd:'hidari ni magaru',zh:'左轉'},{jp:'わたる',rd:'wataru',zh:'穿越'},{jp:'しんごう',rd:'shingou',zh:'紅綠燈'},{jp:'かど',rd:'kado',zh:'角落'},{jp:'むかいがわ',rd:'mukaisawa',zh:'對面'},{jp:'ちかく',rd:'chikaku',zh:'附近'},{jp:'なんぷんかかりますか',rd:'nanpun kakarimasu ka',zh:'要幾分鐘？'},{jp:'ちず',rd:'chizu',zh:'地圖'},{jp:'グーグルマップ',rd:'guuguru mappu',zh:'Google Maps'},{jp:'みちがわからない',rd:'michi ga wakaranai',zh:'不知道路'},{jp:'めのまえ',rd:'me no mae',zh:'眼前'},{jp:'となり',rd:'tonari',zh:'隔壁'}]},
  {week:3,day:4,theme:'住宿飯店',words:[{jp:'ホテル',rd:'hoteru',zh:'飯店'},{jp:'りょかん',rd:'ryokan',zh:'日式旅館'},{jp:'チェックイン',rd:'chekkuin',zh:'入住'},{jp:'チェックアウト',rd:'chekkuauto',zh:'退房'},{jp:'よやく',rd:'yoyaku',zh:'預約'},{jp:'へや',rd:'heya',zh:'房間'},{jp:'シングル',rd:'shinguru',zh:'單人房'},{jp:'ダブル',rd:'daburu',zh:'雙人房'},{jp:'きんえん',rd:'kinen',zh:'禁煙'},{jp:'ちょうしょく',rd:'choushoku',zh:'早餐'},{jp:'タオル',rd:'taoru',zh:'毛巾'},{jp:'かぎ',rd:'kagi',zh:'鑰匙'},{jp:'フロント',rd:'furonto',zh:'櫃台'},{jp:'ルームサービス',rd:'ruumu saabisu',zh:'客房服務'},{jp:'おねがいします',rd:'onegaishimasu',zh:'麻煩你了'}]},
  {week:3,day:5,theme:'觀光景點',words:[{jp:'かんこう',rd:'kankou',zh:'觀光'},{jp:'じんじゃ',rd:'jinja',zh:'神社'},{jp:'おてら',rd:'otera',zh:'寺廟'},{jp:'しろ',rd:'shiro',zh:'城堡'},{jp:'こうえん',rd:'kouen',zh:'公園'},{jp:'はくぶつかん',rd:'hakubutsukan',zh:'博物館'},{jp:'びじゅつかん',rd:'bijutsukan',zh:'美術館'},{jp:'おんせん',rd:'onsen',zh:'溫泉'},{jp:'にわ',rd:'niwa',zh:'庭院'},{jp:'もみじ',rd:'momiji',zh:'紅葉'},{jp:'さくら',rd:'sakura',zh:'櫻花'},{jp:'やま',rd:'yama',zh:'山'},{jp:'うみ',rd:'umi',zh:'海'},{jp:'しぜん',rd:'shizen',zh:'自然'},{jp:'にゅうじょうけん',rd:'nyuujouken',zh:'入場券'}]},
  {week:3,day:6,theme:'天氣',words:[{jp:'てんき',rd:'tenki',zh:'天氣'},{jp:'はれ',rd:'hare',zh:'晴天'},{jp:'くもり',rd:'kumori',zh:'陰天'},{jp:'あめ',rd:'ame',zh:'雨'},{jp:'ゆき',rd:'yuki',zh:'雪'},{jp:'かぜ',rd:'kaze',zh:'風'},{jp:'あつい',rd:'atsui',zh:'熱'},{jp:'さむい',rd:'samui',zh:'冷'},{jp:'すずしい',rd:'suzushii',zh:'涼爽'},{jp:'あたたかい',rd:'atatakai',zh:'溫暖'},{jp:'むしあつい',rd:'mushiatsui',zh:'悶熱'},{jp:'かさ',rd:'kasa',zh:'雨傘'},{jp:'にわかあめ',rd:'niwaka ame',zh:'陣雨'},{jp:'たいふう',rd:'taifuu',zh:'颱風'},{jp:'きおん',rd:'kion',zh:'氣溫'}]},
  {week:3,day:7,theme:'緊急情況',words:[{jp:'たすけて',rd:'tasukete',zh:'救命！'},{jp:'きけん',rd:'kiken',zh:'危險'},{jp:'かじ',rd:'kaji',zh:'火災'},{jp:'どろぼう',rd:'dorobou',zh:'小偷'},{jp:'まよった',rd:'mayotta',zh:'迷路了'},{jp:'なくした',rd:'nakushita',zh:'弄丟了'},{jp:'ぬすまれた',rd:'nusumareta',zh:'被偷了'},{jp:'けいさつ',rd:'keisatsu',zh:'警察'},{jp:'きゅうきゅうしゃ',rd:'kyuukyuusha',zh:'救護車'},{jp:'しょうぼうしゃ',rd:'shoubosha',zh:'消防車'},{jp:'たいしかん',rd:'taishikan',zh:'大使館'},{jp:'パスポート',rd:'pasupooto',zh:'護照'},{jp:'ほけん',rd:'hoken',zh:'保險'},{jp:'にほんごがわかりません',rd:'nihongo ga wakarimasen',zh:'我不懂日文'},{jp:'ちゅうごくごはなせますか',rd:'chuugokugo hanasemasu ka',zh:'你說中文嗎？'}]},
  {week:4,day:1,theme:'人物稱謂',words:[{jp:'わたし',rd:'watashi',zh:'我'},{jp:'あなた',rd:'anata',zh:'你'},{jp:'かれ',rd:'kare',zh:'他'},{jp:'かのじょ',rd:'kanojo',zh:'她'},{jp:'ともだち',rd:'tomodachi',zh:'朋友'},{jp:'かぞく',rd:'kazoku',zh:'家人'},{jp:'おとうさん',rd:'otousan',zh:'爸爸'},{jp:'おかあさん',rd:'okaasan',zh:'媽媽'},{jp:'あに',rd:'ani',zh:'哥哥'},{jp:'おとうと',rd:'otouto',zh:'弟弟'},{jp:'あね',rd:'ane',zh:'姊姊'},{jp:'いもうと',rd:'imouto',zh:'妹妹'},{jp:'こども',rd:'kodomo',zh:'小孩'},{jp:'おとな',rd:'otona',zh:'大人'},{jp:'おじさん',rd:'ojisan',zh:'叔叔'}]},
  {week:4,day:2,theme:'形容詞上',words:[{jp:'おおきい',rd:'ookii',zh:'大的'},{jp:'ちいさい',rd:'chiisai',zh:'小的'},{jp:'たかい',rd:'takai',zh:'高的／貴的'},{jp:'ひくい',rd:'hikui',zh:'低的'},{jp:'ながい',rd:'nagai',zh:'長的'},{jp:'みじかい',rd:'mijikai',zh:'短的'},{jp:'おもい',rd:'omoi',zh:'重的'},{jp:'かるい',rd:'karui',zh:'輕的'},{jp:'あたらしい',rd:'atarashii',zh:'新的'},{jp:'ふるい',rd:'furui',zh:'舊的'},{jp:'きれい',rd:'kirei',zh:'漂亮／乾淨'},{jp:'きたない',rd:'kitanai',zh:'髒的'},{jp:'たのしい',rd:'tanoshii',zh:'開心的'},{jp:'かなしい',rd:'kanashii',zh:'悲傷的'},{jp:'いそがしい',rd:'isogashii',zh:'忙碌的'}]},
  {week:4,day:3,theme:'形容詞下',words:[{jp:'おいしい',rd:'oishii',zh:'好吃'},{jp:'まずい',rd:'mazui',zh:'難吃'},{jp:'おもしろい',rd:'omoshiroi',zh:'有趣的'},{jp:'つまらない',rd:'tsumaranai',zh:'無聊的'},{jp:'むずかしい',rd:'muzukashii',zh:'難的'},{jp:'やさしい',rd:'yasashii',zh:'簡單／溫柔'},{jp:'はやい',rd:'hayai',zh:'快的'},{jp:'おそい',rd:'osoi',zh:'慢的'},{jp:'あかるい',rd:'akarui',zh:'明亮的'},{jp:'くらい',rd:'kurai',zh:'暗的'},{jp:'うるさい',rd:'urusai',zh:'吵的'},{jp:'しずか',rd:'shizuka',zh:'安靜的'},{jp:'べんり',rd:'benri',zh:'方便的'},{jp:'たいせつ',rd:'taisetsu',zh:'重要的'},{jp:'すき',rd:'suki',zh:'喜歡'}]},
  {week:4,day:4,theme:'動詞上',words:[{jp:'いく',rd:'iku',zh:'去'},{jp:'くる',rd:'kuru',zh:'來'},{jp:'かえる',rd:'kaeru',zh:'回去'},{jp:'みる',rd:'miru',zh:'看'},{jp:'きく',rd:'kiku',zh:'聽／問'},{jp:'はなす',rd:'hanasu',zh:'說話'},{jp:'よむ',rd:'yomu',zh:'讀'},{jp:'かく',rd:'kaku',zh:'寫'},{jp:'たべる',rd:'taberu',zh:'吃'},{jp:'のむ',rd:'nomu',zh:'喝'},{jp:'かう',rd:'kau',zh:'買'},{jp:'うる',rd:'uru',zh:'賣'},{jp:'もつ',rd:'motsu',zh:'拿'},{jp:'おく',rd:'oku',zh:'放置'},{jp:'とる',rd:'toru',zh:'拿取'}]},
  {week:4,day:5,theme:'動詞下',words:[{jp:'する',rd:'suru',zh:'做'},{jp:'ある',rd:'aru',zh:'有（物）'},{jp:'いる',rd:'iru',zh:'有（人）'},{jp:'わかる',rd:'wakaru',zh:'明白'},{jp:'しる',rd:'shiru',zh:'知道'},{jp:'おもう',rd:'omou',zh:'認為'},{jp:'みせる',rd:'miseru',zh:'給…看'},{jp:'おしえる',rd:'oshieru',zh:'告訴／教'},{jp:'てつだう',rd:'tetsudau',zh:'幫忙'},{jp:'まつ',rd:'matsu',zh:'等待'},{jp:'はいる',rd:'hairu',zh:'進入'},{jp:'でる',rd:'deru',zh:'出去'},{jp:'あく',rd:'aku',zh:'打開'},{jp:'しまる',rd:'shimaru',zh:'關閉'},{jp:'つかう',rd:'tsukau',zh:'使用'}]},
  {week:4,day:6,theme:'旅行綜合上',words:[{jp:'りょこう',rd:'ryokou',zh:'旅行'},{jp:'かんこうあんない',rd:'kankou annai',zh:'觀光服務台'},{jp:'パンフレット',rd:'panfuretto',zh:'小冊子'},{jp:'じゆうじかん',rd:'jiyuu jikan',zh:'自由時間'},{jp:'しゃしん',rd:'shashin',zh:'照片'},{jp:'しゃしんをとる',rd:'shashin wo toru',zh:'拍照'},{jp:'いっしょに',rd:'issho ni',zh:'一起'},{jp:'ひとりで',rd:'hitori de',zh:'一個人'},{jp:'スマートフォン',rd:'sumaatofon',zh:'智慧型手機'},{jp:'じゅうでん',rd:'juuden',zh:'充電'},{jp:'WIFI',rd:'wai fai',zh:'無線網路'},{jp:'パスワード',rd:'pasuwaado',zh:'密碼'},{jp:'コンセント',rd:'konsento',zh:'插座'},{jp:'ゴミばこ',rd:'gomibako',zh:'垃圾桶'},{jp:'にゅうじょうけん',rd:'nyuujouken',zh:'入場券'}]},
  {week:4,day:7,theme:'旅行綜合下',words:[{jp:'もうすぐ',rd:'mousugu',zh:'快到了'},{jp:'まだ',rd:'mada',zh:'還沒'},{jp:'もう',rd:'mou',zh:'已經'},{jp:'ぜんぶ',rd:'zenbu',zh:'全部'},{jp:'すこし',rd:'sukoshi',zh:'一點點'},{jp:'たくさん',rd:'takusan',zh:'很多'},{jp:'ちょっと',rd:'chotto',zh:'稍微'},{jp:'とても',rd:'totemo',zh:'非常'},{jp:'あまり',rd:'amari',zh:'不太（搭配否定）'},{jp:'ぜんぜん',rd:'zenzen',zh:'完全不'},{jp:'だいたい',rd:'daitai',zh:'大概'},{jp:'はじめて',rd:'hajimete',zh:'第一次'},{jp:'またきたい',rd:'mata kitai',zh:'還想再來'},{jp:'たのしかった',rd:'tanoshikatta',zh:'很開心（過去）'},{jp:'またね',rd:'matane',zh:'下次見'}]},
];
var GDB=[
  {week:1,id:'w1g1',title:'〜は〜です',sub:'「…是…」基本句型',tag:'核心',pattern:{jp:'〔名詞A〕は〔名詞B〕です',rd:'[A] wa [B] desu',zh:'A 是 B'},note:'「は」在這裡唸「wa」不唸「ha」，是日文最基礎的句型，相當於中文的「是」。',examples:[{jp:'わたしはたびびとです。',rd:'Watashi wa tabibito desu.',zh:'我是旅行者。'},{jp:'これはえきです。',rd:'Kore wa eki desu.',zh:'這裡是車站。'},{jp:'あのひとはてんいんさんです。',rd:'Ano hito wa ten\'in san desu.',zh:'那個人是店員。'}],quizzes:[{q:'「我是台灣人。」',hint:'台灣人＝たいわんじん',choices:['わたしはたいわんじんです。','わたしがたいわんじんです。','わたしもたいわんじんです。','わたしにたいわんじんです。'],ans:0,exp:'わたし は たいわんじん です ── A は B です 基本句型。'},{q:'「這個是菜單。」',hint:'菜單＝メニュー，這個＝これ',choices:['これにメニューです。','これはメニューです。','これをメニューです。','これでメニューです。'],ans:1,exp:'「これ は メニュー です」，は 表示「是」。'}]},
  {week:1,id:'w1g2',title:'〜はじゃないです',sub:'「…不是…」否定',tag:'核心',pattern:{jp:'〔名詞〕は〔名詞〕じゃないです',rd:'[A] wa [B] ja nai desu',zh:'A 不是 B'},note:'「じゃないです」是口語否定，等同正式的「ではありません」，旅行中口語版完全 OK。',examples:[{jp:'これはえきじゃないです。',rd:'Kore wa eki ja nai desu.',zh:'這裡不是車站。'},{jp:'わたしはにほんじんじゃないです。',rd:'Watashi wa nihonjin ja nai desu.',zh:'我不是日本人。'},{jp:'ここはホテルじゃないです。',rd:'Koko wa hoteru ja nai desu.',zh:'這裡不是飯店。'}],quizzes:[{q:'「我不是學生。」',hint:'學生＝がくせい',choices:['わたしはがくせいです。','わたしはがくせいじゃないです。','わたしがくせいではあります。','わたしにがくせいじゃない。'],ans:1,exp:'否定用「じゃないです」，接在名詞後面。'},{q:'「這裡不是飯店。」',hint:'飯店＝ホテル，這裡＝ここ',choices:['ここはホテルです。','ここにホテルじゃないです。','ここはホテルじゃないです。','ここがホテルじゃないです。'],ans:2,exp:'ここ は ホテル じゃないです。'}]},
  {week:1,id:'w1g3',title:'〜はどこですか？',sub:'詢問地點萬用句',tag:'旅行必備',pattern:{jp:'〔場所〕はどこですか？',rd:'[basho] wa doko desu ka?',zh:'〜在哪裡？'},note:'「か」放句尾表疑問。旅行最常用句型，空格填地點就能問路！',examples:[{jp:'トイレはどこですか？',rd:'Toire wa doko desu ka?',zh:'廁所在哪裡？'},{jp:'えきはどこですか？',rd:'Eki wa doko desu ka?',zh:'車站在哪裡？'},{jp:'このホテルはどこですか？',rd:'Kono hoteru wa doko desu ka?',zh:'這間飯店在哪裡？'}],quizzes:[{q:'「出口在哪裡？」',hint:'出口＝でぐち',choices:['でぐちはどこですか？','でぐちはなんですか？','でぐちはいつですか？','でぐちはだれですか？'],ans:0,exp:'詢問地點用「どこですか」！'},{q:'「便利商店在哪裡？」',hint:'便利商店＝コンビニ',choices:['コンビニはなんですか？','コンビニにどこですか？','コンビニはどこですか？','コンビニがどこですか？'],ans:2,exp:'コンビニ は どこ です か？'}]},
  {week:2,id:'w2g1',title:'〜をください',sub:'「請給我…」點餐購物',tag:'旅行必備',pattern:{jp:'〔もの〕をください',rd:'[mono] wo kudasai',zh:'請給我〜'},note:'「を」是受格助詞，「ください」是「請給我」。點餐購物最直接的說法。',examples:[{jp:'これをください。',rd:'Kore wo kudasai.',zh:'請給我這個。'},{jp:'みずをふたつください。',rd:'Mizu wo futatsu kudasai.',zh:'請給我兩杯水。'},{jp:'このサイズをください。',rd:'Kono saizu wo kudasai.',zh:'請給我這個尺寸。'}],quizzes:[{q:'「請給我菜單。」',hint:'菜單＝メニュー',choices:['メニューがください。','メニューにください。','メニューをください。','メニューはください。'],ans:2,exp:'「を」是受格助詞，固定搭配「ください」。'},{q:'「請給我三個。」',hint:'三個＝みっつ',choices:['みっつはください。','みっつをください。','みっつにください。','みっつからください。'],ans:1,exp:'〔數量〕をください。'}]},
  {week:2,id:'w2g2',title:'〜はいくらですか？',sub:'詢問價格',tag:'旅行必備',pattern:{jp:'〔もの〕はいくらですか？',rd:'[mono] wa ikura desu ka?',zh:'〜多少錢？'},note:'「いくら」是「多少錢」，結構和「どこですか」完全一樣，換個疑問詞就好！',examples:[{jp:'これはいくらですか？',rd:'Kore wa ikura desu ka?',zh:'這個多少錢？'},{jp:'ひとつはいくらですか？',rd:'Hitotsu wa ikura desu ka?',zh:'一個多少錢？'},{jp:'このセットはいくらですか？',rd:'Kono setto wa ikura desu ka?',zh:'這個套餐多少錢？'}],quizzes:[{q:'「這個蛋糕多少錢？」',hint:'蛋糕＝ケーキ',choices:['このケーキはどこですか？','このケーキはいくらですか？','このケーキはなんですか？','このケーキはいつですか？'],ans:1,exp:'問價格用「いくらですか」！'},{q:'「一個多少錢？」',hint:'一個＝ひとつ',choices:['ひとつはどこですか？','ひとつがいくらですか？','ひとつはいくらですか？','ひとつをいくらですか？'],ans:2,exp:'ひとつ は いくら です か？'}]},
  {week:2,id:'w2g3',title:'〜でいいですか？',sub:'確認方式手段',tag:'實用',pattern:{jp:'〔手段〕でいいですか？',rd:'[shudan] de ii desu ka?',zh:'用〜可以嗎？'},note:'「で」表示手段或方式，「いいですか」是「可以嗎」，常用於確認付款方式。',examples:[{jp:'カードでいいですか？',rd:'Kaado de ii desu ka?',zh:'用信用卡可以嗎？'},{jp:'えいごでいいですか？',rd:'Eigo de ii desu ka?',zh:'用英文可以嗎？'},{jp:'これでいいですか？',rd:'Kore de ii desu ka?',zh:'這樣可以嗎？'}],quizzes:[{q:'「用現金可以嗎？」',hint:'現金＝げんきん',choices:['げんきんはいいですか？','げんきんをいいですか？','げんきんでいいですか？','げんきんにいいですか？'],ans:2,exp:'「で」表手段，「いいですか」詢問是否可以。'},{q:'「用英文可以嗎？」',hint:'英文＝えいご',choices:['えいごにいいですか？','えいごはいいですか？','えいごをいいですか？','えいごでいいですか？'],ans:3,exp:'えいご で いいですか。'}]},
  {week:3,id:'w3g1',title:'〜に行きます',sub:'「去〜」目的地',tag:'核心',pattern:{jp:'〔場所〕に行きます',rd:'[basho] ni ikimasu',zh:'去〜'},note:'「に」表示方向或目的地，「行きます」是「去」的禮貌形。',examples:[{jp:'えきにいきます。',rd:'Eki ni ikimasu.',zh:'去車站。'},{jp:'とうきょうにいきます。',rd:'Toukyou ni ikimasu.',zh:'去東京。'},{jp:'このホテルにいきたいです。',rd:'Kono hoteru ni ikitai desu.',zh:'我想去這間飯店。'}],quizzes:[{q:'「我去京都。」',hint:'京都＝きょうと',choices:['きょうとをいきます。','きょうとがいきます。','きょうとにいきます。','きょうとはいきます。'],ans:2,exp:'移動目的地用「に」。'},{q:'「去便利商店。」',hint:'便利商店＝コンビニ',choices:['コンビニへいきます。','コンビニをいきます。','コンビニにいきます。','コンビニのいきます。'],ans:2,exp:'「に」表示方向目的地。'}]},
  {week:3,id:'w3g2',title:'〜てください',sub:'「請〜」禮貌請求',tag:'旅行必備',pattern:{jp:'〔動詞て形〕ください',rd:'[doushi te-kei] kudasai',zh:'請〜'},note:'「て形」接「ください」就是「請〜」。幾個旅行常用て形要背下來！',examples:[{jp:'まっすぐいってください。',rd:'Massugu itte kudasai.',zh:'請直走。'},{jp:'ゆっくりはなしてください。',rd:'Yukkuri hanashite kudasai.',zh:'請說慢一點。'},{jp:'しゃしんをとってください。',rd:'Shashin wo totte kudasai.',zh:'請幫我拍照。'}],quizzes:[{q:'「請等一下。」',hint:'等＝まつ → て形：まって',choices:['まつください。','まちください。','まってください。','まてください。'],ans:2,exp:'「まつ」的て形是「まって」。'},{q:'「請說慢一點。」',hint:'說＝はなす → て形：はなして',choices:['ゆっくりはなすください。','ゆっくりはなしてください。','ゆっくりはなしください。','ゆっくりはなくてください。'],ans:1,exp:'「はなす」的て形是「はなして」。'}]},
  {week:3,id:'w3g3',title:'〜たいです',sub:'「想〜」表達願望',tag:'實用',pattern:{jp:'〔動詞ます形語幹〕たいです',rd:'[doushi-masu gokan] tai desu',zh:'想〜'},note:'把動詞「ます」去掉，加「たいです」就是「想〜」。食べます → 食べたいです（想吃）。',examples:[{jp:'すしをたべたいです。',rd:'Sushi wo tabetai desu.',zh:'我想吃壽司。'},{jp:'おんせんにはいりたいです。',rd:'Onsen ni hairitai desu.',zh:'我想泡溫泉。'},{jp:'きょうとにいきたいです。',rd:'Kyouto ni ikitai desu.',zh:'我想去京都。'}],quizzes:[{q:'「我想喝咖啡。」',hint:'喝＝のみます → のみたいです',choices:['コーヒーをのみます。','コーヒーをのみたいです。','コーヒーをのむです。','コーヒーがのみたいです。'],ans:1,exp:'「のみます」去ます加たいです＝のみたいです。'},{q:'「我想拍照。」',hint:'拍照＝とります → とりたいです',choices:['しゃしんをとりたいです。','しゃしんをとってたいです。','しゃしんをとりますたいです。','しゃしんをとたいです。'],ans:0,exp:'「とります」→「とり」＋「たいです」。'}]},
  {week:4,id:'w4g1',title:'〜ましたか？',sub:'「〜了嗎？」過去式',tag:'核心',pattern:{jp:'〔動詞〕ましたか？',rd:'[doushi] mashita ka?',zh:'〜了嗎？'},note:'「ます」→「ました」是現在式變過去式，加「か」是疑問句。',examples:[{jp:'チェックインしましたか？',rd:'Chekkuin shimashita ka?',zh:'辦理入住了嗎？'},{jp:'もうたべましたか？',rd:'Mou tabemashita ka?',zh:'已經吃了嗎？'},{jp:'よやくしましたか？',rd:'Yoyaku shimashita ka?',zh:'預約了嗎？'}],quizzes:[{q:'「已經買票了嗎？」',hint:'買＝かいます→かいました',choices:['きっぷをかいますか？','きっぷをかいましたか？','きっぷをかうか？','きっぷをかったか？'],ans:1,exp:'過去式疑問：ます→ました＋か。'},{q:'「去了大阪嗎？」',hint:'去＝いきます→いきました',choices:['おおさかにいきますか？','おおさかにいきましたか？','おおさかにいきたいですか？','おおさかにいきますたか？'],ans:1,exp:'「いきます→いきました」，加か是「去了嗎？」'}]},
  {week:4,id:'w4g2',title:'〜がすきです',sub:'「喜歡〜」好惡表達',tag:'實用',pattern:{jp:'〔もの〕がすきです／きらいです',rd:'[mono] ga suki/kirai desu',zh:'喜歡／討厭〜'},note:'注意！表達喜好用「が」不用「は」。すき＝喜歡，きらい＝討厭，だいすき＝超喜歡。',examples:[{jp:'すしがすきです。',rd:'Sushi ga suki desu.',zh:'我喜歡壽司。'},{jp:'からいたべものがきらいです。',rd:'Karai tabemono ga kirai desu.',zh:'我討厭辣的食物。'},{jp:'おんせんがだいすきです。',rd:'Onsen ga daisuki desu.',zh:'我超愛溫泉。'}],quizzes:[{q:'「我喜歡拉麵。」',hint:'拉麵＝ラーメン，喜好用「が」',choices:['ラーメンはすきです。','ラーメンをすきです。','ラーメンがすきです。','ラーメンにすきです。'],ans:2,exp:'表達喜好固定用「が」。'},{q:'「我非常喜歡日本。」',hint:'非常喜歡＝だいすき',choices:['にほんはだいすきです。','にほんをだいすきです。','にほんにだいすきです。','にほんがだいすきです。'],ans:3,exp:'すき/きらい/だいすき 前面固定用「が」。'}]},
  {week:4,id:'w4g3',title:'〜てもいいですか？',sub:'「可以〜嗎？」請求許可',tag:'旅行必備',pattern:{jp:'〔動詞て形〕もいいですか？',rd:'[doushi te-kei] mo ii desu ka?',zh:'可以〜嗎？'},note:'「てもいいですか」是請求許可的禮貌說法，比直接要求更有禮貌。',examples:[{jp:'しゃしんをとってもいいですか？',rd:'Shashin wo totte mo ii desu ka?',zh:'可以拍照嗎？'},{jp:'ここにすわってもいいですか？',rd:'Koko ni suwatte mo ii desu ka?',zh:'可以坐這裡嗎？'},{jp:'クレジットカードをつかってもいいですか？',rd:'Kurejitto kaado wo tsukatte mo ii desu ka?',zh:'可以用信用卡嗎？'}],quizzes:[{q:'「可以試穿嗎？」',hint:'試穿→て形：きてみて',choices:['きてみるもいいですか？','きてみてもいいですか？','きてもいいですか？','きてみていいですか？'],ans:1,exp:'「きてみて」＋「もいいですか」＝可以試穿嗎？'},{q:'「可以進去嗎？」',hint:'進去＝はいる → て形：はいって',choices:['はいるもいいですか？','はいってもいいですか？','はいりもいいですか？','はいりてもいいですか？'],ans:1,exp:'「はいる」的て形是「はいって」。'}]},
];
var REF=[
  {title:'助詞總整理',rows:[{jp:'は（wa）',zh:'主題標記 → A は B です'},{jp:'が（ga）',zh:'強調主語・喜好 → すきです 前面用'},{jp:'を（wo）',zh:'受格 → ～をください・～をたべます'},{jp:'に（ni）',zh:'方向目的地 → ～にいきます'},{jp:'で（de）',zh:'手段方式 → カードで・えいごで'},{jp:'の（no）',zh:'所有格 → わたしのかばん（我的包包）'},{jp:'も（mo）',zh:'也 → わたしもです（我也是）'},{jp:'か（ka）',zh:'疑問句尾 → ～ですか？'}]},
  {title:'動詞變化（現在→過去）',rows:[{jp:'いきます → いきました',zh:'去 → 去了'},{jp:'たべます → たべました',zh:'吃 → 吃了'},{jp:'のみます → のみました',zh:'喝 → 喝了'},{jp:'かいます → かいました',zh:'買 → 買了'},{jp:'します → しました',zh:'做 → 做了'},{jp:'きます → きました',zh:'來 → 來了'}]},
  {title:'て形快速對照',rows:[{jp:'いきます → いって',zh:'去'},{jp:'たべます → たべて',zh:'吃'},{jp:'のみます → のんで',zh:'喝'},{jp:'まちます → まって',zh:'等'},{jp:'します → して',zh:'做'},{jp:'はなします → はなして',zh:'說話'},{jp:'とります → とって',zh:'拿取'},{jp:'はいります → はいって',zh:'進入'}]},
  {title:'〜たいです 變化',rows:[{jp:'いきます → いきたいです',zh:'想去'},{jp:'たべます → たべたいです',zh:'想吃'},{jp:'のみます → のみたいです',zh:'想喝'},{jp:'みます → みたいです',zh:'想看'},{jp:'かいます → かいたいです',zh:'想買'}]},
];
